version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - major
  - package-ecosystem: "gradle"
    directories:
      - "/"
      - "common"
      - "core"
      - "gateway"
      - "oauth2"
      - "rest"
      - "voice"
    schedule:
      interval: "cron"
      cronjob: "0 0 * * *"
    groups:
      gradle-wrapper:
        patterns:
          - "gradle-wrapper"
      minor-and-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "gradle-wrapper"
