version: 2
updates:

    -   package-ecosystem: "gradle"
        directory: "/"
        schedule:
            interval: "daily"
        reviewers:
            - "quanticc"
            - "austinv11"
            - "darichey"
        commit-message:
            prefix: "gradle"
            include: "scope"

    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "daily"
        reviewers:
            - "quanticc"
            - "austinv11"
            - "darichey"
        commit-message:
            prefix: "github-actions"
            include: "scope"
